### ISSUE TITLE
USER STORY: Initial Deployment

### ISSUE THREAD

**Issue by jmanager25** [jmanager25/ExpenseTrack#17]
As a **developer** I want **to deploy the initial project on Heroku** so that **I can test the application on a live server**

## Acceptance Criteria:

 * The project is successfully deployed on Heroku and can be accessed via a web browser.
 
## Tasks

- [x] Create an app on Heroku.
- [x] Create a new PostgreSQL database instance
- [x] Create an env.py file and set the environment variables.
- [x] Modify the settings of the project.
- [x] Connect the Heroku app to the database.
- [x] Deploy the initial project on Heroku.

##Epic: #15
