### ISSUE TITLE
USER STORY: Add New Expense

### ISSUE THREAD

**Issue by jmanager25** [jmanager25/ExpenseTrack#25]
As a **user** I want **to be able to add a new expense** so that **I can keep track of my spending**

## Acceptance Criteria

 * The user should be able to enter the amount of the expense.
 * The user should be able to select a category for the expense.
 * The user should be able to add a note or description for the expense.

## Tasks

- [x] Create a form for adding new expenses that include fields for amount, category, and notes.
- [x] Create a view that allows the user to submit the form and save the expense to the database.
- [x] Create a confirmation message that lets the user know the expense has been added successfully.
