### ISSUE TITLE
USER STORY : Add New Income

### ISSUE THREAD

**Issue by jmanager25** [jmanager25/ExpenseTrack#26]
As a **user** I want **to be able to add a new income** so that **I can keep track of my earnings**

## Acceptance Criteria

 * The user should be able to enter the amount of the income.
 * The user should be able to select a category for the income.
 * The user should be able to add a note or description for the income.

## Tasks

- [x] Create a form for adding new income that includes fields for amount, category, and notes.
- [x] Create a view that allows the user to submit the form and save the income to the database.
- [x] Create a confirmation message that lets the user know the income has been added successfully.
