### ISSUE TITLE
USER STORY: Edit Expense

### ISSUE THREAD

**Issue by jmanager25** [jmanager25/ExpenseTrack#27]
As a **user** I want **to be able to edit an expense item** so that **so that I can correct a mistake**

## Acceptance Criteria

 * User can select an expense item from their list to edit.
 * User can update any editable fields of the selected expense item.
 * User can save the changes made to the expense item.

## Tasks

- [x] Create an "Edit" button for each expense item in the expense list.
- [x] Implement a form for editing the selected expense item.
- [x] Update the expense item in the database with the edited values.
- [x] Create a confirmation message that lets the user know the expense has been edited successfully.
