### ISSUE TITLE
USER STORY: Edit Income

### ISSUE THREAD

**Issue by jmanager25** [jmanager25/ExpenseTrack#28]
As a **user** I want **to be able to edit an income item** so that **I can correct a mistake**

## Acceptance Criteria

 * User can select an income item from their list to edit.
 * User can update any editable fields of the selected income item.
 * User can save the changes made to the income item.

## Tasks

- [x] Create an "Edit" button for each income item in the list.
- [x] Implement a form for editing the selected income item.
- [x] Update the income item in the database with the edited values.
- [x] Create a confirmation message that lets the user know the Income has been edited successfully.
