### ISSUE TITLE
USER STORY: Delete Expense

### ISSUE THREAD

**Issue by jmanager25** [jmanager25/ExpenseTrack#29]
As a ** user** I want **to be able to delete an expense item** so that **I can remove it from my records and keep my financial data accurate**

## Acceptance Criteria

 * The user should be able to delete an expense item from the expense list view.
 * The user should receive a confirmation message before the expense item is deleted.
 * The deleted expense item should be removed from the expense list and any associated calculations should be updated accordingly.

## Tasks

- [x] Implement a "delete" button for each expense item in the expense list view.
- [x] Create a confirmation message for the user before the expense item is deleted.
- [x] Implement the functionality to remove the expense item from the expense list and update any associated calculations.
