### ISSUE TITLE
USER STORY: Delete Income Item

### ISSUE THREAD

**Issue by jmanager25** [jmanager25/ExpenseTrack#30]
As a **user** I want **to be able to delete an income item** so that **I can remove it from my records and keep my financial data accurate**

## Acceptance Criteria

 * The user should be able to delete an income item from the list view.
 * The user should receive a confirmation message before the income item is deleted.
 * The deleted income item should be removed from the list and any associated calculations should be updated accordingly.

## Tasks

- [x] Implement a "delete" button for each income item in the list view.
- [x] Create a confirmation message for the user before the income item is deleted.
- [x] Implement the functionality to remove the income item from the list and update any associated calculations.
