### ISSUE TITLE
USER STORY: Adding Savings Goals

### ISSUE THREAD

**Issue by jmanager25** [jmanager25/ExpenseTrack#31]
As a **user** I want **to be able to add a savings goal** so that **I can track my progress toward achieving it**

## Acceptance Criteria

 * The user should be able to create a savings goal with a title, description, target amount, and target date.
 * The user should be able to view their progress toward the savings goal and how much they have left to save.

## Tasks

- [x] Create a form for adding Savings Goals that include a title, description, target amount, and target date.
- [x] Implement the backend functionality to store and retrieve savings goal data.
- [x] Create the logic to calculate progress toward savings goals.
