### ISSUE TITLE
USER STORY: Deleting Savings Goals

### ISSUE THREAD

**Issue by jmanager25** [jmanager25/ExpenseTrack#33]
As a **user** I want **to be able to delete my savings goals** so that **I can keep my records clean and organized**

## Acceptance Criteria

 * The user should be able to select a savings goal and delete it from the list of active goals.
 * The user should receive a confirmation message before the savings goal is permanently deleted.

## Tasks

- [x] Create a button to allow the user to delete a savings goal.
- [x] Implement a process to remove all data associated with the savings goal from the database.
- [x] Add a confirmation message to ensure that the user wants to permanently remove the savings goal.
