### ISSUE TITLE
USER STORY: Create Category

### ISSUE THREAD

**Issue by jmanager25** [jmanager25/ExpenseTrack#45]
As a **user** I want **to be able to create my own categories** so that **I can organize my transactions according to their purpose**

## Acceptance Criteria

 * Users should be able to select the newly created category when adding their income or expenses.

## Tasks

- [x] Create a new app for categories
- [x] Create views that allows users to create the category
- [x] Create the template to add categories
