### ISSUE TITLE
USER STORY: Edit Category

### ISSUE THREAD

**Issue by jmanager25** [jmanager25/ExpenseTrack#46]
As a **user** I want **to be able to edit the categories** so that **i can correct any mistake I make when creating them**

## Acceptance Criteria

 * Users should be able to click the edit button and update the category

## Tasks

- [x] Create the template to edit category
- [x] create the views for updating category
- [x] Set the URL to the templates
