### ISSUE TITLE
USER STORY: Delete Categories

### ISSUE THREAD

**Issue by jmanager25** [jmanager25/ExpenseTrack#47]
As a **User** I want **to be able to delete the categories** so that **I can keep only the categories that i want and need**

## Acceptance Criteria

 * Users should be able to delete the a category from the category list
 * User should receive a confirmation message before the income item is deleted.

## Tasks

- [x] Create the view for deleting category
- [x] Add de url to render the template
- [x] Create the delete category template
